### ISSUE TITLE
[询问] Titanium SDK

### ISSUE THREAD

**Issue by Shallong** [mdsb100/titanium-good-practices#2]
啊，你好啊

最近因为某些开发的事情接触到了这个SDK（大概两个月左右）
不过后来才发现国内的资源少得可怜，或者说基本没有吧
之前全在官网API和问题区那里看，最近也才搜到gitTio这个工具，然后今天又试着搜了一下shareSDK的时候发现这里的
想必你是写这篇文章 (http://mob.com/index.php/Share/Index/mediaItem/id/28) 的作者（因为只有一半，所以之前问了客服，但是客服说说论坛关掉了也找不到当时的作者了）
（好了不扯了。。）

我现在也碰到点问题，所以想来请教和询问一下！其中感觉问题最大的应该是微信的分享和ListView滚动卡顿情况（可以说是类似微博或者微信那一类的应用吧）。

就微信分享的话，想问一下那个 iPhone-ShareSDK-Titaniuim-Module-Demo 基于现阶段的SDK版本（3.4）和shareSDK的版本是可以实现的么？有没有之前那个论坛帖子的教程呢？

感谢 🙏

（最后再扯一个题外话，如果你知道这个框架在国内的发展团队的话可以告诉我么？我好像觉得这个可以拼一下的。。或者是说在国内如果能搞起来的话会不会是一个机会呢。。？）

抱歉来创建一个Issue啊，感觉这个对于现在的自己来说的确有些吃力。。如果OC再强大一点的话或许可以解决一部分问题

Shallong.
2015-1-4

**Comment by mdsb100** [comment]
问题一，基于3.4微信分享肯定可以的。
问题二，我之前写的教程被shareSDK搞丢了，我也去问过客服。也许我会找时间重新写个教程。因为有很多坑，不写教程还真是不行。
问题三，我们都用的是listView。我觉得你可以去官方看一下。
问题四：这个我不清楚。我们自己团队也转向原生了（这不是否定titanium）。但是可以肯定中国还是有不少人在用的，建议你加点qq群123668856。
问题五：这个么，我不敢妄下定论，但是你如果要写module的话，绝对是对自己能力的一大提升。

**Comment by Shallong** [comment]
Thanks.

**Comment by mdsb100** [comment]
你可以watch下，等我教程写好了，你就收到通知了。
