### ISSUE TITLE
Titanium模块咨询

### ISSUE THREAD

**Issue by jackgreentemp** [mdsb100/titanium-good-practices#4]
您好，请问：
模块工程能直接导入吗？

试了一下，您建好的模块工程，导入后不能编译

**Comment by mdsb100** [comment]
你怎么导入的？ios android?

**Comment by jackgreentemp** [comment]
解决了，需要修改titanium.xcconfig中TITANIUM_SDK的路径
谢谢。

**Comment by jackgreentemp** [comment]
您好：
在ios模块工程platform目录下有一个存放图片资源的文件夹“Resource”，将模块打包到app工程后，发现app工程中对应的模块目录中platform文件夹下没有存放资源的文件夹，想请教下可能是哪儿的问题？

**Comment by mdsb100** [comment]
platform/iphone 下

**Comment by mdsb100** [comment]
你加个ti qq群吧: 329933158

**Comment by jackgreentemp** [comment]
是不是图片资源要放到platform/iphone/下...

**Comment by jackgreentemp** [comment]
是不是图片资源要放到platform/iphone/下...

**Comment by mdsb100** [comment]
是。

**Comment by jackgreentemp** [comment]
非常感谢！

**Comment by jackgreentemp** [comment]
您好，图片资源文件夹必须放入一个xxx.bundle吗？

**Comment by mdsb100** [comment]
我觉得你应该仔细看下文档。http://docs.appcelerator.com/platform/latest/#!/guide/iOS_Module_Development_Guide

http://docs.appcelerator.com/platform/latest/#!/guide/Alloy_Quick_Start

**Comment by jackgreentemp** [comment]
官方教程里没有介绍，ios模块的资源文件应该放在什么地方...

**Comment by mdsb100** [comment]
你说的是module还是项目。不管哪个档案显然是有的。

**Comment by mdsb100** [comment]
http://docs.appcelerator.com/platform/latest/#!/guide/Alloy_Concepts
别说你不用alloy。
app/assets/iphone

**Comment by jackgreentemp** [comment]
app的图片资源放在app/assets/iphone，ios module的图片资源放在module工程的什么目录，platform/iphone下？

**Comment by jackgreentemp** [comment]
您好，知道怎么回事了，module的图片资源放到module工程的assets目录下，调用时使用
NSString *path = [NSString stringWithFormat:@"modules/%@/foo.png",[self moduleId]];
NSURL *url = [TiUtils toURL:path proxy:self];
UIImage *image = [TiUtils image:url proxy:self];
这样的方式来调用

您的教程中有一个方法-(NSString*)getPathToModuleAsset:(NSString*) fileName就是做类似的事情吧。

**Comment by mdsb100** [comment]
嗯
